### ISSUE TITLE
Incorrect coordinate parsing with locale ru_RU.UTF-8

### ISSUE THREAD

**Issue by woodroof** [libkml/libkml#193] opened 2015-04-22 11:19 UTC
geometry.cc:96 and other places: strtod is dependent on locale.

**Comment by rashadkm** [comment] 2015-04-23 20:43
what is the problem here? it shouldnt depend on locale? I dont understand your issue. Please be more precise

**Comment by woodroof** [comment] 2015-04-24 05:10
Delimiter and decimal point are dependent on locale. For example if locale is german or russian "." is used as a delimiter and "," is used as a decimal point. As a result "54.2" transforms into 54.
So, yes, number serialization/deserialization shouldn't use any locale-dependent function.

**Comment by rashadkm** [comment] 2015-04-24 17:25
Ok. So a different implementation of strtod must be added. 

@dndanik, do you have a different implementation?

**Comment by rashadkm** [comment] 2015-04-25 20:27
I had locale as french where , is used a decimal point. So 54,2 is a actually 54.2

here is the output of locale

```
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

testing a simple code gives:

```
strtod output of 54,3 is 54.00 
strtod output of 54.3 is 54.30

code:

#include <stdio.h>
#include <stdlib.h>

int main ()
{
  printf ("strtod output of 54,3 is %.2f \n", strtod ("54,3", NULL));
  printf ("strtod output of 54.3 is %.2f \n", strtod ("54.3", NULL));
  return 0;
}
```

**Comment by rashadkm** [comment] 2016-03-09 15:52
forcing LC_NUMERIC to C using newlocale, uselocale has fixed the issue. please test if possible

**Comment by woodroof** [comment] 2016-03-10 08:32
Your example was incorrect since locale wasn't used.
Correct example:

```
#include <stdio.h>
#include <stdlib.h>
#include <locale>

int main ()
{
  std::locale::global(std::locale("ru_RU.UTF-8"));
  printf ("strtod output of 54,3 is %.2f \n", strtod ("54,3", NULL));
  printf ("strtod output of 54.3 is %.2f \n", strtod ("54.3", NULL));
  return 0;
}
```

Output:

```
strtod output of 54,3 is 54,30 
strtod output of 54.3 is 54,00
```

Forcing external code to use LC_NUMERIC="C" is not a solution. Correct implementation MUST NOT use any locale-dependent function.

**Comment by rashadkm** [comment] 2016-03-10 08:50
yes. the old example was wrong. Thanks for correct example.
I set LC_NUMERIC =C just for doing conversion not globally in the system. After doing strtod and parsting stuff, the locale is reverted back to its original value. see here. https://github.com/libkml/libkml/commit/d8bd6666a3214f0c7b985f8c7c57af44e56528cf . locale is reverted when in the destructor call of LocaleC class. https://github.com/libkml/libkml/commit/d8bd6666a3214f0c7b985f8c7c57af44e56528cf

**Comment by woodroof** [comment] 2016-03-10 09:11
I think d8bd666 is wrong since you do not store the original locale (return value of setlocale) and do not restore it in LocaleC::~LocaleC.
So, the locale is NOT reverted back to its original value for the calling thread.

**Comment by rashadkm** [comment] 2016-03-10 12:20
I got a fix for this - https://github.com/libkml/libkml/commit/543666e29f62cb157427c8c95485dd1a88b06ebc

will you be interested in adding a unittest in libkml/tests/kml/base perhaps ?

**Comment by woodroof** [comment] 2016-03-11 05:41
New commit is even worse, cause it uses windows-only function _configthreadlocale. Yet again, only correct way is to not play with locales and just use locale-independent functions. This functions cannot fail unlike library calls like newlocale/uselocale. And you can't correctly handle such errors!
Using printf is not a correct way since is results in returning invalid kml to user code. Correct way of handling errors in library is to return invalid value with error message.

But if you still want to do it, use return value of uselocale:

```
LocaleC::LocaleC() :
  m_PrevLocale(0)
{
  if (locale_t new_locale = newlocale(LC_NUMERIC_MASK, "C", 0))
  {
    m_PrevLocale = uselocale(new_locale);
  }
}

LocaleC::~LocaleC()
{
  if (m_PrevLocale)
  {
    locale_t our_locale = uselocale(m_PrevLocale);
    freelocale(our_locale);
  }
}
```

P.S. I really hate code style for class members like m_PrevLocale

**Comment by rashadkm** [comment] 2016-03-11 07:15
Let me know if I understand correctly when you saying locale independent functions. strtod is locale dependent and to convert string to double I need to use it or roll a new strtod method. That is to use strtod first and after it fails it changes the decimal character with dot (.) or comma and then call strtod with it

so StrtodWithoutLocale("1.25") in russian locale it converts 1.25 to 1,25 and then call strtod("1,25") which gives correct result. 

in the case of geometry.cc see the [code](https://github.com/libkml/libkml/blob/master/src/kml/dom/geometry.cc#L59). If a custom strtod to be added as mentioned above. Most of these code needs to be changed as it checks if strtod is failed when parsing the strings
What you think?

**Comment by woodroof** [comment] 2016-03-15 09:20
```
std::string to_string(double value)
{
  std::ostringstream out;
  out.imbue(std::locale::classic());
  out << value;
  return out.str();
}
double from_string(const std::string &str)
{
  double value;
  std::istringstream in(str);
  in.imbue(std::locale::classic());
  in >> value;
  return value;
}
double my_strtod(char* str, char** endptr)
{
  const std::streamsize size = static_cast<std::streamsize>(std::strlen(str));

  std::stringbuf buf;
  buf.pubsetbuf(str, size);

  std::istream in(&buf);
  in.imbue(std::locale::classic());

  double value;
  in >> value;

  *endptr = str + (size - buf.in_avail());

  return value;
}
```

**Comment by rashadkm** [comment] 2016-03-18 13:28
Thanks for the code. The issue is geometry.cc is not only about strtod() but also about splitting a cstring based on comma. Currently geometry.cc uses strtod and when error occurred in strtod such as occurrence of a comma character or whitespace, it stops parsing.  split if whitespace for comma found is not good here because  input strings cannot be always in proper format. see tests/kml/dom/geometry_test.cc. 

This is wrong strategy and should never be used because of locale problems. First lon, lat, alt must be picked up and then a locale independent string to double conversion should be employed to make it perfect.

I updated existing string to double method based on your code above in kmlbase::ToString to be locale independent.

All test are passing on my side. Please feel free to check it and reopen if the issue persists.

https://github.com/libkml/libkml/pull/233

**Closed as completed** 2016-03-19 06:11 UTC
